<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.de-gupta</groupId>
        <artifactId>security.parent</artifactId>
        <version>0.1.0</version>
    </parent>

    <artifactId>security.dependencies.bom</artifactId>
    <version>0.2.4-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>${project.artifactId}</name>
    <description>A Maven BOM for shared dependencies used by the commons-security stack</description>
    <url>https://github.com/de-gupta/security.dependencies.bom.git</url>

    <properties>
        <aletheia.version>0.7.0</aletheia.version>
        <athena.version>0.5.0</athena.version>

        <jjwt.version>0.13.0</jjwt.version>
        <junit.jupiter.version>5.13.1</junit.jupiter.version>
        <assertj.core.version>3.27.3</assertj.core.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.github.de-gupta</groupId>
                <artifactId>aletheia</artifactId>
                <version>${aletheia.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.de-gupta</groupId>
                <artifactId>athena</artifactId>
                <version>${athena.version}</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-api</artifactId>
                <version>${jjwt.version}</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-impl</artifactId>
                <version>${jjwt.version}</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-jackson</artifactId>
                <version>${jjwt.version}</version>
            </dependency>
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter</artifactId>
                <version>${junit.jupiter.version}</version>
            </dependency>
            <dependency>
                <groupId>org.assertj</groupId>
                <artifactId>assertj-core</artifactId>
                <version>${assertj.core.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <scm>
        <connection>scm:git:ssh://git@github.com/de-gupta/security.dependencies.bom.git</connection>
        <developerConnection>scm:git:ssh://git@github.com/de-gupta/security.dependencies.bom.git</developerConnection>
        <url>https://github.com/de-gupta/security.dependencies.bom.git</url>
        <tag>HEAD</tag>
    </scm>
</project>